
stages:
  - pages

pages:
  image: ruanpienaar/python_mkdocs:latest
  stage: pages
  script:
    - mkdocs build
    - mkdir .public
    - cp -r site/* .public
    - mv .public public
 artifacts:
    paths:
    - public
